#--------------------------------------------------------------------------------------------#
░██████╗██╗░░██╗██╗░░░██╗███████╗███████╗██╗░░░░░███████╗░██████╗░░█████╗░███╗░░░███╗███████╗
██╔════╝██║░░██║██║░░░██║██╔════╝██╔════╝██║░░░░░██╔════╝██╔════╝░██╔══██╗████╗░████║██╔════╝
╚█████╗░███████║██║░░░██║█████╗░░█████╗░░██║░░░░░█████╗░░██║░░██╗░███████║██╔████╔██║█████╗░░
░╚═══██╗██╔══██║██║░░░██║██╔══╝░░██╔══╝░░██║░░░░░██╔══╝░░██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░
██████╔╝██║░░██║╚██████╔╝██║░░░░░██║░░░░░███████╗███████╗╚██████╔╝██║░░██║██║░╚═╝░██║███████╗
╚═════╝░╚═╝░░╚═╝░╚═════╝░╚═╝░░░░░╚═╝░░░░░╚══════╝╚══════╝░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝
#--------------------------------------------------------------------------------------------#

use-permissions: false #
# Permissions:
# shufflegame.start -> Start Game
# shufflegame.setup -> Settings Game
# shufflegame.stop -> Stop Game 