#--------------------------------------------------------------------------------------------#
#██████╗██╗░░██╗██╗░░░██╗███████╗███████╗██╗░░░░░███████╗░██████╗░░█████╗░███╗░░░███╗███████╗
#██╔════╝██║░░██║██║░░░██║██╔════╝██╔════╝██║░░░░░██╔════╝██╔════╝░██╔══██╗████╗░████║██╔════╝
#╚█████╗░███████║██║░░░██║█████╗░░█████╗░░██║░░░░░█████╗░░██║░░██╗░███████║██╔████╔██║█████╗░░
#░╚═══██╗██╔══██║██║░░░██║██╔══╝░░██╔══╝░░██║░░░░░██╔══╝░░██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░
#██████╔╝██║░░██║╚██████╔╝██║░░░░░██║░░░░░███████╗███████╗╚██████╔╝██║░░██║██║░╚═╝░██║███████╗
#╚═════╝░╚═╝░░╚═╝░╚═════╝░╚═╝░░░░░╚═╝░░░░░╚══════╝╚══════╝░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝
#--------------------------------------------------------------------------------------------#

use-permissions: false # if you want use permissions

# Permissions:
# shufflegame.start -> Start Game
# shufflegame.setup -> Settings Game
# shufflegame.stop -> Stop Game
# shufflegame.join -> Join Game
# shufflegame.leave -> Leave Game
# shufflegame.pause -> Pause game